version: '3.8'

services:
  webserver:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "8080:80"  # Port yang dapat diakses oleh host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro       # Kustomisasi konfigurasi nginx
      - ./index.html:/usr/share/nginx/html/index.html  # Laman HTML Kustom
    networks:
      - app-network

  database:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: exampledb
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Volume untuk persisten data PostgreSQL
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"  # PGAdmin diakses melalui port 5050
    volumes:
      - pgadmin_data:/var/lib/pgadmin  # Volume untuk menyimpan data PGAdmin
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
