version: '3.8'

services:
  webserver:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "8080:80"  # Port yang dapat diakses oleh host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro       # Kustomisasi konfigurasi nginx
      - ./index.html:/usr/share/nginx/html/index.html  # Laman HTML Kustom
      - ./nginx_logs:/var/log/nginx  # Volume untuk log nginx
    networks:
      - app-network
    restart: unless-stopped

  database:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: exampledb
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Volume untuk persisten data PostgreSQL
    networks:
      - app-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"  # PGAdmin diakses melalui port 5050
    volumes:
      - pgadmin_data:/var/lib/pgadmin  # Volume untuk menyimpan data PGAdmin
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"  # Port default Redis
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  nginx_logs:
    driver: local
